const words = [
    "apple", "grape", "table", "chair", "mouse", "plant", "world", "bread", "cloud", "smile",
    "latch", "flame", "track", "proud", "brick", "stand", "quiet", "brave", "stone", "sweep",
    "charm", "truth", "dance", "voice", "storm", "black", "white", "sharp", "crisp", "blink",
    "gauge", "rough", "chill", "blend", "flute", "focus", "slope", "light", "chalk", "cover",
    "level", "lucky", "crazy", "trick", "swing", "color", "mango", "pearl", "urban", "steep",
    "float", "flush", "dream", "flock", "stage", "flown", "shift", "creek", "trend", "pulse",
    "write", "shiny", "split", "brisk", "grasp", "stare", "crowd", "climb", "pride", "quest",
    "fancy", "shout", "grove", "skate", "spice", "glide", "shine", "bloom", "ridge", "blaze",
    "check", "groan", "cling", "trace", "grill", "drift", "flash", "chase", "tiger", "prism",
    "booth", "troop", "broke", "score", "roast", "crash", "cloak", "spear", "stack", "field",
    "pivot", "blend", "grind", "valor", "frail", "grain", "slide", "chore", "smash", "twist",
    "greet", "crane", "chess", "flask", "skull", "sleek", "hound", "angle", "maple", "frost",
    "stock", "prize", "table", "badge", "fraud", "flare", "blunt", "stain", "flute", "blend",
    "vault", "steer", "sworn", "pluck", "frame", "crisp", "delta", "shove", "carve", "shear",
    "bluff", "pitch", "fuzzy", "plush", "swift", "glory", "feast", "notch", "brink", "trace",
    "frank", "latch", "trail", "grape", "crown", "creed", "spark", "elbow", "flora", "spend",
    "foamy", "drain", "blown", "evoke", "grill", "noble", "spine", "raven", "brass", "hover",
    "shave", "grime", "pluck", "piano", "carol", "brush", "gleam", "proud", "straw", "sweat",
    "vivid", "crisp", "bliss", "shelf", "sting", "spoon", "gloss", "crack", "clean", "grape",
    "steep", "fetch", "grace", "grind", "shine", "frill", "brace", "ridge", "cheer", "claim",
    "spout", "truck", "groan", "lever", "frank", "shove", "brisk", "pulse", "spark", "layer",
    "hatch", "ridge", "valor", "pitch", "chill", "thorn", "charm", "chord", "grasp", "clerk",
    "stalk", "twist", "drift", "shout", "creek", "swept", "stack", "spare", "plaza", "brave",
    "pivot", "trick", "sheer", "quilt", "flint", "stall", "chore", "gleam", "press", "brick",
    "storm", "chime", "shaky", "grape", "feast", "shear", "chalk", "climb", "plain", "twirl",
    "brink", "shine", "clash", "froth", "grind", "stack", "clove", "glint", "brace", "frail",
    "claim", "sheep", "plate", "chess", "flake", "grasp", "sleek", "trend", "chime", "crown",
    "prism", "flood", "spear", "steep", "stage", "spend", "flair", "booth", "creek", "grill",
    "crash", "froze", "pluck", "bland", "grime", "shelf", "graft", "grace", "brisk", "blaze",
    "drift", "proud", "shear", "cloud", "smile", "broke", "vault", "craze", "chalk", "flake",
    "flint", "stone", "sharp", "grill", "chord", "smash", "shine", "blend", "brace", "craze"
]

export default words